name: Publish Docker
on:
  push:
    branches:
      - ver/1.8.8
      - docker-test
jobs:
  push:
    name: Push image to registry
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Escape branch name
        run: |
          ls -la
          ref="${github_ref////-}"
          echo "git_ref=$ref" >> $GITHUB_ENV
        env:
          github_ref: ${{ github.ref_name }}
      - name: Login to GH Registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
      - name: Create build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/build.Dockerfile
          tags: localhost:5000/kig-builder:${{ env.git_ref }}
          load: true
          # push: ${{ github.event_name != 'pull_request' }}
      - name: Inspect
        run: |
          df -h
          docker buildx du
          docker images
      - name: Create HotSpot image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: docker.pkg.github.com/projectkig/kigpaper/kig-paper:${{ env.git_ref }}
          build-args: |
            git_ref=${{ env.git_ref }}
      - name: Create J9 image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/j9.Dockerfile
          tags: docker.pkg.github.com/projectkig/kigpaper/kig-paper:${{ env.git_ref }}_j9
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            git_ref=${{ env.git_ref }}