name: Publish Docker
on:
  push:
    branches:
      - ver/1.8.8
jobs:
  push:
    name: Push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GH Registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
      - name: Create build image
        uses: docker/build-push-action@v2
        with:
          file: docker/build.Dockerfile
          tags: projectkig/kigpaper/kig-paper:${{ github.ref_name }}_build
          load: true
          # push: ${{ github.event_name != 'pull_request' }}
      - name: Create HotSpot image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: projectkig/kigpaper/kig-paper:${{ github.ref_name }}
          build-args: |
            git_ref=${{ github.ref_name }}
      - name: Create J9 image
        uses: docker/build-push-action@v2
        with:
          file: docker/j9.Dockerfile
          tags: projectkig/kigpaper/kig-paper:${{ github.ref_name }}_j9
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            git_ref=${{ github.ref_name }}