name: Gradle CI
on: [push, pull_request]
jobs:
  build:
    name: Build Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Git identity
        run: git config --global user.name "Phoenix" && git config --global user.email "actions@github.com"
      - name: Build
        run: ./build.sh
